// thoda zada ts ho gya idhar
export enum SkillNames {
  JS = "js",
  TS = "ts",
  HTML = "html",
  CSS = "css",
  REACT = "react",
  CSHARP = "csharp",
  NEXTJS = "nextjs",
  TAILWIND = "tailwind",
  BOOTSTRAP = "bootstrap",
  ANTDESIGN = "antdesign",
  WEBPACK = "webpack",
  SASS = "sass",
  GIT = "git",
  GITHUB = "github",
  PRETTIER = "prettier",
  NPM = "npm",
  DART = "dart",
  FLUTTER = "flutter",
  CLERK = "clerk",
  CONVEX = "convex",
  SHADCN = "shadcn",
  CESIUM = "cesium",
  BLAZOR = "blazor",
  VERCEL = "vercel",
}
export type Skill = {
  id: number;
  name: string;
  label: string;
  shortDescription: string;
  color: string;
  icon: string;
};
export const SKILLS: Record<SkillNames, Skill> = {
  [SkillNames.JS]: {
    id: 1,
    name: "js",
    label: "JavaScript",
    shortDescription: "yeeting code into the DOM since '95, no cap! 💯🚀",
    color: "#f0db4f",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
  },
  [SkillNames.TS]: {
    id: 2,
    name: "ts",
    label: "TypeScript",
    shortDescription: "JavaScript's overachieving cousin flexing hard 💯🔒",
    color: "#007acc",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
  },
  [SkillNames.HTML]: {
    id: 3,
    name: "html",
    label: "HTML",
    shortDescription: "the internet's OG markup king 👑🔥",
    color: "#e34c26",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
  },
  [SkillNames.CSS]: {
    id: 4,
    name: "css",
    label: "CSS",
    shortDescription: "styling with the ultimate drip 💁‍♂️✨",
    color: "#563d7c",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
  },
  [SkillNames.REACT]: {
    id: 5,
    name: "react",
    label: "React",
    shortDescription: `"use using" 
using use = useUsing("use")`,
    color: "#61dafb",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
  },
  [SkillNames.CSHARP]: {
    id: 6,
    name: "csharp",
    label: "C#",
    shortDescription: "Microsoft's MVP language, slick and strong 💪🔵",
    color: "#68217a",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg",
  },
  [SkillNames.NEXTJS]: {
    id: 7,
    name: "nextjs",
    label: "Next.js",
    shortDescription: "The drama queen of front-end frameworks 👑📜",
    color: "#fff",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
  },
  [SkillNames.TAILWIND]: {
    id: 8,
    name: "tailwind",
    label: "Tailwind",
    shortDescription: "utility classes hitting different 🌪️🔥",
    color: "#38bdf8",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg",
  },
  [SkillNames.BOOTSTRAP]: {
    id: 9,
    name: "bootstrap",
    label: "Bootstrap",
    shortDescription: "the OG frontend toolkit in a purple suit 🎩💜",
    color: "#7952b3",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg",
  },
  [SkillNames.ANTDESIGN]: {
    id: 10,
    name: "antdesign",
    label: "Ant Design",
    shortDescription: "React UI kit with pure corporate drip 💼✨",
    color: "#1890ff",
    icon: "https://avatars.githubusercontent.com/u/12101536?s=200&v=4",
  },
  [SkillNames.WEBPACK]: {
    id: 11,
    name: "webpack",
    label: "Webpack",
    shortDescription: "the OG bundler that glues it all together 📦💣",
    color: "#8dd6f9",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/webpack/webpack-original.svg",
  },
  [SkillNames.SASS]: {
    id: 12,
    name: "sass",
    label: "Sass",
    shortDescription: "CSS with attitude and variables 💅🎀",
    color: "#cc6699",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg",
  },
  [SkillNames.GIT]: {
    id: 13,
    name: "git",
    label: "Git",
    shortDescription: "the code's personal bodyguard 🕵️‍♂️🔄",
    color: "#f1502f",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
  },
  [SkillNames.GITHUB]: {
    id: 14,
    name: "github",
    label: "GitHub",
    shortDescription: "sliding into those pull requests, IYKYK 🐙",
    color: "#000",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg",
  },
  [SkillNames.PRETTIER]: {
    id: 15,
    name: "prettier",
    label: "Prettier",
    shortDescription: "making your code not a mess 🧹✨",
    color: "#f7b93a",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/prettier/prettier-original.svg",
  },
  [SkillNames.NPM]: {
    id: 16,
    name: "npm",
    label: "NPM",
    shortDescription: "package manager said 'I gotchu' 📦💯",
    color: "#cb3837",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/npm/npm-original-wordmark.svg",
  },
  [SkillNames.DART]: {
    id: 17,
    name: "dart",
    label: "Dart",
    shortDescription: "Google's language for beautiful UIs 🎨🦋",
    color: "#0175c2",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dart/dart-original.svg",
  },
  [SkillNames.FLUTTER]: {
    id: 18,
    name: "flutter",
    label: "Flutter",
    shortDescription: "cross-platform app dev but make it spicy 🌶️📱",
    color: "#02569b",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flutter/flutter-original.svg",
  },
  [SkillNames.CLERK]: {
    id: 19,
    name: "clerk",
    label: "Clerk",
    shortDescription: "authentication made ridiculously simple 🔐✨",
    color: "#3b82f6",
    icon: "https://avatars.githubusercontent.com/u/71596369?s=200&v=4",
  },
  [SkillNames.CONVEX]: {
    id: 20,
    name: "convex",
    label: "Convex",
    shortDescription: "The new kid on the backend block 🎒🧑‍💻",
    color: "#000",
    icon: "https://avatars.githubusercontent.com/u/87790208?s=200&v=4",
  },
  [SkillNames.SHADCN]: {
    id: 21,
    name: "shadcn",
    label: "shadcn/ui",
    shortDescription: "the cleanest UI kit in town ✨⚡",
    color: "#000",
    icon: "https://avatars.githubusercontent.com/u/139895814?s=200&v=4",
  },
  [SkillNames.CESIUM]: {
    id: 22,
    name: "cesium",
    label: "Cesium",
    shortDescription: "3D geospatial maps on steroids 🌍🚀",
    color: "#5dadec",
    icon: "https://avatars.githubusercontent.com/u/1929371?s=200&v=4",
  },
  [SkillNames.BLAZOR]: {
    id: 23,
    name: "blazor",
    label: "Blazor",
    shortDescription: "C# meets WebAssembly, no JavaScript needed ⚙️🔥",
    color: "#512bd4",
    icon: "https://avatars.githubusercontent.com/u/19903516?s=200&v=4",
  },
  [SkillNames.VERCEL]: {
    id: 24,
    name: "vercel",
    label: "Vercel",
    shortDescription: "deploy fast, then touch grass 🚀🌿",
    color: "#000",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vercel/vercel-original.svg",
  },
};


export const themeDisclaimers = {
  light: [
    "Warning: Light mode emits a gazillion lumens of pure radiance!",
    "Caution: Light mode ahead! Please don't try this at home.",
    "Only trained professionals can handle this much brightness. Proceed with sunglasses!",
    "Brace yourself! Light mode is about to make everything shine brighter than your future.",
    "Flipping the switch to light mode... Are you sure your eyes are ready for this?",
  ],
  dark: [
    "Light mode? I thought you went insane... but welcome back to the dark side!",
    "Switching to dark mode... How was life on the bright side?",
    "Dark mode activated! Thanks you from the bottom of my heart, and my eyes too.",
    "Welcome back to the shadows. How was life out there in the light?",
    "Dark mode on! Finally, someone who understands true sophistication.",
  ],
};

